#Finding a Spliced Motif

def fasta_into_dict(fasta):
    fasta_list = fasta.split()
    fasta_dict = {}
    for line in fasta_list:
        if line[0] == '>':
            header = line[1:]
            fasta_dict[header] = []
        else:
            fasta_dict[header].append(line[:])  #creates list within value {'header': ['ABS', 'ABC']}
    for header in fasta_dict:
        fasta_dict[header] = ''.join(fasta_dict[header])
    return fasta_dict


fasta = '''>Rosalind_7496
TATTACTGGAAAGTTTCTAGAAGTTTTGTAATTCACTTGCTGGTTTATAACATGGCGCAT
TTGCGGCCGCAGGCAATAAAGCGTCTTGTTGTTGCAACGAGTATGAGTACACCGACATAT
AATATTCATTGCGTAAACATAGTCTTAGCGCTAGGCGCAGCATGGGGGTGAACTTACACG
CTTGGTGCTGTATACAGCTGGGAAGCGTCTAACACCGTTGATCAGGTGCGTTACTTCTGT
CACTAGGCGCGTCACGTACCGGGGTGCCGTGTCGCTCCGGGTTTGGAACAATCGCGTAGC
TCTCGTGACCCCCTAAAGGAGAGAAGAATGGCTGTCGGTGCTTGGCGCGTCAACCAAACG
TCATAGTGCATCTATAAATCATGTCGGTAGCGACAGGCCTCTGATGCTGGTCCTCCACGT
CGTGAGCTGATAGCAAGGAATTATGCGAAGCACTCGGCGGTGCCTTCTACTACAATATAG
TGCTACTATGTCAGGAAGACCTAATACGACCCTATATTCGGGGCGCGCGGTACGCCTATC
ACAATCAATTTATGTGAGATAAGAAAGTCTCCCTACAGAAAATAAACCTCTTCTACCGTA
TATAAGCTCGGCGAGTCCCTGAACCATGCGCCATGCCCAACCTTGGCCCGGGCCACGTAC
GCGATTGAAATTTTGACTATTGTTTAGTATGTAAGACTTAGTCGTCGTTGGAACCCTCTG
TGTGAGTCCTGAGGTTGTTGACAGTAGGAAGGCTGGTTAGATTTTATGGCAGGGCAGTGA
TCTTACCCTATGCTCAATCTTGGACTCGGGGGGGTTTGCCAACGTTGCTGTATTGAGGCG
CATTGTGCGGATCATATGTAGGAGGGTAGCGATCGATCACCCTAAGTAGATAAAAAGGAC
CCCGTCGTCATCGCGAGGAGACGGCCGTTACTACTGCCACTAGAACTTCTCCTGTCTATC
CTCCCAAAGTCTGATTCACGGGGACGATCCCCTATTTTGG
>Rosalind_5330
TATCGTGGCGCGGGGATTGGTGTT'''

fasta_dict = fasta_into_dict(fasta)

sequence_list = []
for header, sequence in fasta_dict.items():
    sequence_list.append(sequence)

s = sequence_list[0]
t = sequence_list[1]

position_list = []
a = 0
for i in range(len(t)):             #iterates over substring
    position = s.find(t[i], a)      #finds character of substring beginning by position of previous character
    position_list.append(str(position+1))
    a = position+1

print(' '.join(position_list))
